
title = "gitleaks config"

[extend]
# useDefault will extend the base configuration with the default gitleaks config:
# https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[[allowlists]]
description = "Global Allow Lists"
regexes = [
  # Docstring examples of TaskRun short-name -> service-name stripping
  # e.g. 'auth-xyz98' -> 'auth', 'mariadb-gen01-abc12' -> 'mariadb-gen01'
  '''[a-z][a-z0-9-]+-[a-z0-9]{5}' -> '[a-z][a-z0-9-]+''',
  # FAKE GITHUB CLIENT SECRET
  '''ghs_16C7e42F292c6912E771''',
]